FROM kathara/base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wireguard-tools \
    wireguard-go \
    iproute2 \
    iptables \
    iputils-ping \
    procps \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 51820/udp
